### ISSUE TITLE
create "output device" plugin that exports model in UFP format

### ISSUE THREAD

**Issue by goergch** [IUNO-TDM/ProductionManagerCuraPlugin#1]
https://github.com/Ultimaker/UraniumExampleOutputDevicePlugin
https://ultimaker.com/en/resources/52467-extension-plugins

**Comment by goergch** [comment]
If using UFP (Ultimaker format package), Cura writes a zipped folder containing gcode and thumbnail
also the current filename is available

**Comment by bockha** [comment]
UFP is a file format introduced with [Ultimaker Cura 3.3 on April 24th 2018](https://github.com/Ultimaker/Cura/releases/tag/3.3.0).
