### ISSUE TITLE
implement this user story

### ISSUE THREAD

**Issue by goergch** [IUNO-TDM/ProductionManagerCuraPlugin#2]
1. The user imports a 3d model as stl file into Ultimaker Cura
2. The user configures the slicer settings and optimizes them for the print
3. The user then "pushes" the sliced 3d-model (stl and generated gcode) to the Production Manager #1, #3 
3a. The user has to define a name for the object he wants to push (depends on #6)
3b. The settings have to be pushed to Production Manager (Machine type, nozzles, materials,...)
4. The user opens the Production Manager UI in the browser
5. The user selects the before pushed object, selects a suitable machine and starts the print

depends on #1 
depends on #4 
depends on #3

**Comment by bockha** [comment]
3b is already contained in gcode
