### ISSUE TITLE
Talk to a REST API at the ProductionManager

### ISSUE THREAD

**Issue by goergch** [IUNO-TDM/ProductionManagerCuraPlugin#3]
The Cura Plugin has to send the sliced 3d model -> gcode to the production manager.

This should be done via a REST interface at the production manager, which has to be defined 

A POST call would be preferable.

**Comment by goergch** [comment]
https://github.com/IUNO-TDM/ProductionManager/blob/master/interface.yaml

POST localhost:3042/api/objects/local

**Comment by bockha** [comment]
```
import requests

url = 'http://localhost:3042/api/localobjects'
data = {'title':(None, "Foo Bar"), 'file':('foobar.ufp', open('/tmp/foobar.ufp', 'rb'))}

resp = requests.post(url, files=data)
```
